export type pitchingStats = {
  wins: number;
  losses: number;
  era: number;
  gamesPlayed: number;
  gamesStarted: number;
  inningsPitched: string;
  strikeOuts: number;
  baseOnBalls: number;
  hits: number;
  homeRuns: number;
  whip: number;
  saves: number;
  blownSaves: number;
  completeGames: number;
  shutouts: number;
  battersFaced: number;
  numberOfPitches: number;
  strikeoutsPer9Inn: number;
  walksPer9Inn: number;
  hitsPer9Inn: number;
};

export type playerStats = {
  gamesPlayed: number;
  groundOuts: number;
  airOuts: number;
  runs: number;
  doubles: number;
  triples: number;
  homeRuns: number;
  strikeOuts: number;
  baseOnBalls: number;
  intentionalWalks: number;
  hits: number;
  hitByPitch: number;
  avg: number;
  atBats: number;
  obp: number;
  slg: number;
  ops: number;
  caughtStealing: number;
  stolenBases: number;
  stolenBasePercentage: number;
  groundIntoDoublePlay: number;
  numberOfPitches: number;
  plateAppearances: number;
  totalBases: number;
  rbi: number;
  leftOnBase: number;
  sacBunts: number;
  sacFlies: number;
  babip: number;
  groundOutsToAirouts: number;
  catchersInterference: number;
  atBatsPerHomeRun: number;
  pitching?: pitchingStats;
}